import {ThemeConfig} from 'antd';
import colors from '../../assets/styles/abstracts/color';
import fonts from '../../assets/styles/abstracts/fonts';
import sizes from '../../assets/styles/abstracts/sizes';

export const themeConfig: ThemeConfig = {
    token: {
        controlHeight: 45,
    },
    components: {
        Button: {
            borderRadius: sizes.borderRadiusSm,
            controlHeight: 40,
            fontFamily: fonts.font,
            colorPrimaryActive: 'none',
            colorPrimaryHover: 'none',
            colorPrimaryBorderHover: 'none',
            controlTmpOutline: 'none',
            colorBorder: 'none',
            controlOutline: 'none',
            controlOutlineWidth: 0,
            colorPrimaryBg: 'none',
            colorLink: 'none',
            colorLinkActive: 'none',
            colorLinkHover: 'none',
            colorPrimaryBorder: 'none',
            colorBorderBg: 'none',
            colorPrimary: colors.gray,
            colorBgSpotlight: colors.gray,

        },
        Table: {
            borderRadius: 0,
            colorBorderSecondary: 'none',
            colorTextHeading: colors.white,
            fontFamily: fonts.font,
            paddingSM: 10,
            paddingMD: 10,
            paddingLG: 10,
            paddingContentHorizontalLG: 10,
            paddingContentVerticalLG: 10,
            paddingXS: 10,
            controlPaddingHorizontal: 10,
            controlPaddingHorizontalSM: 10,
            paddingContentVerticalSM: 10,
            colorPrimaryHover: colors.gray,
            colorPrimary: colors.gray,
        },
        Input: {
            colorBorder: colors.gray,
            colorText: colors.black,
            colorTextPlaceholder: colors.gray,
            colorBgContainer: 'transparent',
            borderRadius: sizes.borderRadiusInput,
            controlHeight: 40,
            paddingSM: 23,
            fontSize: 16,
            fontFamily: fonts.font,
            colorPrimaryHover: colors.blue,
            marginSM: 5,
            marginMD: 5,
            marginLG: 5,
            marginXS: 5,
            colorTextLabel: colors.blueCircle,
        },
        Select: {
            borderRadius: sizes.borderRadiusInput,
            controlHeight: 40,
            colorBorder: colors.gray,
            controlItemBgActive: 'transparent',
            colorPrimaryHover: colors.blue,
            colorTextPlaceholder: colors.gray,
            colorText: colors.black,
            colorPrimary: colors.gray,
            colorPrimaryBorderHover: colors.gray,
            colorIconHover: colors.blue,
            paddingSM: 23,
            fontFamily: fonts.font,
            colorIcon: colors.gray,
            fontSizeIcon: 20,
            marginSM: 5,
            marginMD: 5,
            marginLG: 5,
            marginXS: 5,

        },
        DatePicker: {
            colorPrimaryHover: colors.blueCircle,
            borderRadius: sizes.borderRadiusInput,
            controlHeight: 40,
            paddingSM: 23,
            colorBorder: colors.gray,
            colorText: colors.black,
            colorPrimary: colors.blueCircle,
            fontFamily: fonts.font,
            colorTextPlaceholder: colors.gray,
            controlItemBgActive: colors.blueCircle,
            paddingLG: 0,
            colorBgLayout: colors.blueCircle,
        },
        Checkbox: {
            borderRadius: 8,
            borderRadiusSM: 8,
            colorPrimaryBorder: '#949494',
            lineWidthBold: 1,
            fontFamily: fonts.font,
            colorIconHover: '#949494',
            colorIcon: '#949494',
            controlHeight: 24,
            controlHeightLG: 24,
            controlHeightSM: 16,
            colorBorder: '#949494',
        },
        Form: {
            fontFamily: 'Lato Regular',
            fontSize: 16,
            fontWeightStrong: 400,
            marginSM: 0,
            colorTextLabel: colors.blueCircle,
            fontFamilyCode: 'Lato Regular',
            marginMD: 22,
            marginLG: 22,
            marginXS: 22, colorText: colors.darkBlue,
            controlHeight: 30,
        },
        Modal: {
            colorBgMask: 'rgba(0, 0, 0, 0.25)',
            borderRadiusLG: 12,
            paddingContentHorizontalLG: 20,
            paddingContentVerticalLG: 20,
            paddingMD: 20,
        },
    },
};
